test: add test by circleci config validate

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,13 +16,21 @@ workflows:
           filters:
             tags:
               only: /.*/
+      - test:
+          requires:
+            - build
+          filters:
+            tags:
+              only: /.*/
           
       - publish-dev-of-pr:
           requires:
             - build
+            - test
       - publish:
           requires:
             - build
+            - test
           filters:
             tags:
               only: /.*/
@@ -40,6 +48,27 @@ jobs:
           root: .
           paths:
             - "*"
+  test:
+    executor: circleci
+    steps:
+      - attach_workspace:
+          at: .
+      - run:
+          name: Validate config
+          command: |
+            for file in $(ls tests); do
+              filepath=$(mktemp)
+              if cat orb.yml tests/$file | circleci config validate - > $filepath 2>&1; then
+                continue
+              else
+                COLOR_1="\e[31;1m"
+                COLOR_OFF="\e[m"
+                echo "${COLOR_1}$file is failed${COLOR_OFF}" >&2
+                echo $filepath >&2
+                exit 1
+              fi
+            done
+
   publish:
     executor: circleci
     steps:
